from abc import ABC, abstractmethod
from typing import Dict, Any, List
import uuid

class QuestionProvider(ABC):
    @abstractmethod
    def get_question(self, 
                     exam: str, 
                     subject: str, 
                     topics: List[str], 
                     difficulty: str, 
                     language: str, 
                     excluded_ids: List[str], 
                     session_context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Returns a raw question dictionary that adheres to the contract.
        Must include:
        question_id, question_text, options, correct_option, explanation, difficulty, subject, topic,
        provider_type, ai_status
        """
        pass

class DevelopmentFallbackProvider(QuestionProvider):
    def get_question(self, 
                     exam: str, 
                     subject: str, 
                     topics: List[str], 
                     difficulty: str, 
                     language: str, 
                     excluded_ids: List[str], 
                     session_context: Dict[str, Any]) -> Dict[str, Any]:
        
        # This is a development-only synthetic mock implementation.
        # It generates a structurally compliant payload to test the API contract.
        # It does not claim intelligence or AI generation.
        
        fallback_id = f"fallback_{uuid.uuid4().hex[:8]}"
        topic = topics[0] if topics else "General"
        
        return {
            "question_id": fallback_id,
            "question_text": {
                "en": f"[MOCK] Synthetic question for {exam} - {subject} ({topic}) at {difficulty} difficulty?",
                "hi": f"[MOCK] {exam} - {subject} ({topic}) के लिए कृत्रिम प्रश्न ({difficulty})?"
            },
            "options": [
                {"id": "A", "text": {"en": "Option Alpha", "hi": "विकल्प अल्फा"}},
                {"id": "B", "text": {"en": "Option Beta", "hi": "विकल्प बीटा"}},
                {"id": "C", "text": {"en": "Option Gamma", "hi": "विकल्प गामा"}},
                {"id": "D", "text": {"en": "Option Delta", "hi": "विकल्प डेल्टा"}}
            ],
            "correct_option": "B",
            "explanation": {
                "en": "This is a synthetic explanation generated by the development fallback provider.",
                "hi": "यह विकास फ़ॉलबैक प्रदाता द्वारा उत्पन्न एक कृत्रिम स्पष्टीकरण है।"
            },
            "difficulty": difficulty,
            "subject": subject,
            "topic": topic,
            "provider_type": "DEVELOPMENT_FALLBACK",
            "ai_status": "NOT_CONFIGURED"
        }
