from typing import Dict, Any, List

class QuestionValidationService:
    @staticmethod
    def validate_provider_output(raw_question: Dict[str, Any], language: str) -> bool:
        """
        Validates the structure and content of a question generated by a provider.
        Returns True if valid, False otherwise.
        """
        try:
            # 1. Check required top-level fields
            required_fields = ["question_id", "question_text", "options", "correct_option", "explanation", "difficulty", "subject", "topic"]
            for field in required_fields:
                if field not in raw_question:
                    return False
            
            # 2. Check exactly 4 options
            options = raw_question.get("options", [])
            if not isinstance(options, list) or len(options) != 4:
                return False
            
            # 3. Check option IDs exactly A, B, C, D
            valid_ids = {"A", "B", "C", "D"}
            option_ids = set()
            option_texts = set()
            
            for opt in options:
                opt_id = opt.get("id")
                if opt_id not in valid_ids:
                    return False
                option_ids.add(opt_id)
                
                # Verify nested text structure
                text_obj = opt.get("text", {})
                if not isinstance(text_obj, dict):
                    return False
                
                en_text = text_obj.get("en", "").strip()
                hi_text = text_obj.get("hi", "").strip()
                
                if language in ["english", "both"] and not en_text:
                    return False
                if language in ["hindi", "both"] and not hi_text:
                    return False
                    
                # 4. Check unique option text (using en as base if available, else hi)
                check_text = en_text if en_text else hi_text
                if check_text:
                    if check_text in option_texts:
                        return False
                    option_texts.add(check_text)

            if option_ids != valid_ids:
                return False
                
            # 5. Check correct_option is valid
            correct_option = raw_question.get("correct_option")
            if correct_option not in valid_ids:
                return False
                
            # 6. Check main question text languages
            q_text = raw_question.get("question_text", {})
            if language in ["english", "both"] and not q_text.get("en", "").strip():
                return False
            if language in ["hindi", "both"] and not q_text.get("hi", "").strip():
                return False
                
            # 7. Check explanation languages
            exp_text = raw_question.get("explanation", {})
            if language in ["english", "both"] and not exp_text.get("en", "").strip():
                return False
            if language in ["hindi", "both"] and not exp_text.get("hi", "").strip():
                return False
                
            # 8. Check valid difficulty
            if raw_question.get("difficulty") not in ["easy", "medium", "hard"]:
                return False
                
            # Note: Uniqueness of question_id against asked_question_ids is verified by the provider loop 
            # or in interview_service. This strictly validates the structural contract.
                
            return True
        except Exception:
            return False
